import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";

import type { ColorData } from "./types";
import { ensureDirectory } from "./utils";

export async function updateBtopColors(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;

	const btopTheme = `# Generated by novashell
# Wallpaper: ${data.wallpaper}

# Main background, empty for terminal default
theme[main_bg]=""

# Main text color
theme[main_fg]="${s.foreground}"

# Title color for boxes
theme[title]="${s.foreground}"

# Highlight color for keyboard shortcuts
theme[hi_fg]="${c.color4}"

# Background color of selected item in processes box
theme[selected_bg]="${c.color4}"

# Foreground color of selected item in processes box
theme[selected_fg]="${s.background}"

# Color of inactive/disabled text
theme[inactive_fg]="${c.color8}"

# Color of text appearing on top of graphs
theme[graph_text]="${s.foreground}"

# Background color of the percentage meters
theme[meter_bg]="${c.color8}"

# Misc colors for processes box including mini cpu graphs
theme[proc_misc]="${c.color5}"

# Cpu box outline color
theme[cpu_box]="${c.color4}"

# Memory/disks box outline color
theme[mem_box]="${c.color2}"

# Net up/down box outline color
theme[net_box]="${c.color1}"

# Processes box outline color
theme[proc_box]="${c.color6}"

# Box divider line and small boxes line color
theme[div_line]="${c.color8}"

# Temperature graph colors
theme[temp_start]="${c.color4}"
theme[temp_mid]="${c.color5}"
theme[temp_end]="${c.color1}"

# CPU graph colors
theme[cpu_start]="${c.color4}"
theme[cpu_mid]="${c.color6}"
theme[cpu_end]="${c.color2}"

# Mem/Disk free meter
theme[free_start]="${c.color2}"
theme[free_mid]="${c.color6}"
theme[free_end]="${c.color4}"

# Mem/Disk cached meter
theme[cached_start]="${c.color5}"
theme[cached_mid]="${c.color4}"
theme[cached_end]="${c.color6}"

# Mem/Disk available meter
theme[available_start]="${c.color3}"
theme[available_mid]="${c.color2}"
theme[available_end]="${c.color6}"

# Mem/Disk used meter
theme[used_start]="${c.color1}"
theme[used_mid]="${c.color5}"
theme[used_end]="${c.color4}"

# Download graph colors
theme[download_start]="${c.color4}"
theme[download_mid]="${c.color2}"
theme[download_end]="${c.color6}"

# Upload graph colors
theme[upload_start]="${c.color5}"
theme[upload_mid]="${c.color1}"
theme[upload_end]="${c.color3}"
`;

	ensureDirectory(`${GLib.get_user_config_dir()}/btop/themes`);

	const btopThemePath = `${GLib.get_user_config_dir()}/btop/themes/pywal.theme`;
	await writeFileAsync(btopThemePath, btopTheme).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write btop theme: ${e.message}`);
	});
}
