import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";
import { execAsync } from "ags/process";

import type { ColorData } from "./types";
import { stripHash } from "./utils";

export function reloadFish(): void {
	const walCachePath = `${GLib.get_user_cache_dir()}/wal/colors.fish`;
	execAsync(["fish", "-c", `source ${walCachePath}`])
		.then(() => {})
		.catch(() => {});
}

export async function generateFishColors(data: ColorData): Promise<void> {
	const c = data.colors;
	const s = data.special;

	const fishColors = `# Generated by novashell - Theme: ${data.name || "pywal"}
# Uses universal variables (-U) so changes propagate to all running fish sessions

set -U fish_color_normal ${stripHash(s.foreground)}
set -U fish_color_command ${stripHash(c.color4)}
set -U fish_color_keyword ${stripHash(c.color5)}
set -U fish_color_quote ${stripHash(c.color2)}
set -U fish_color_redirection ${stripHash(c.color6)}
set -U fish_color_end ${stripHash(c.color5)}
set -U fish_color_error ${stripHash(c.color1)}
set -U fish_color_param ${stripHash(c.color6)}
set -U fish_color_comment ${stripHash(c.color8)}
set -U fish_color_selection --background=${stripHash(c.color8)}
set -U fish_color_search_match --background=${stripHash(c.color8)}
set -U fish_color_operator ${stripHash(c.color6)}
set -U fish_color_escape ${stripHash(c.color5)}
set -U fish_color_autosuggestion ${stripHash(c.color8)}
set -U fish_color_cwd ${stripHash(c.color4)}
set -U fish_color_user ${stripHash(c.color2)}
set -U fish_color_host ${stripHash(c.color4)}
set -U fish_color_host_remote ${stripHash(c.color3)}
set -U fish_color_cancel ${stripHash(c.color1)}

set -U fish_pager_color_progress ${stripHash(c.color8)}
set -U fish_pager_color_prefix ${stripHash(c.color4)}
set -U fish_pager_color_completion ${stripHash(s.foreground)}
set -U fish_pager_color_description ${stripHash(c.color8)}
`;

	const walCachePath = `${GLib.get_user_cache_dir()}/wal/colors.fish`;
	await writeFileAsync(walCachePath, fishColors).catch((e) => {
		console.error(`ColorUtils: Could not write fish colors: ${e}`);
	});
}
