import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";

import type { ColorData, DerivedPalette } from "./types";
import { adjustLightness, copyContentInPlace, ensureDirectory } from "./utils";

const GTK3_BASE_CANDIDATES = [
	"/usr/share/themes/adw-gtk3-dark/gtk-3.0/gtk.css",
	"/usr/share/themes/Adwaita-dark/gtk-3.0/gtk.css",
];

const GTK4_BASE_CANDIDATES = [
	"/usr/share/themes/adw-gtk3-dark/gtk-4.0/gtk.css",
	"/usr/share/themes/Adwaita-dark/gtk-4.0/gtk.css",
];

function resolveBaseImport(candidates: string[], fallback: string): string {
	for (const path of candidates) {
		if (GLib.file_test(path, GLib.FileTest.EXISTS)) {
			return `file://${path}`;
		}
	}

	return fallback;
}

function buildColorOverrides(data: ColorData, p: DerivedPalette): string {
	const s = data.special;
	const c = data.colors;

	const viewBg = adjustLightness(s.background, 8);
	const cardBg = adjustLightness(s.background, 13);
	const popoverBg = adjustLightness(s.background, 8);

	return `@define-color accent_bg_color ${p.accent};
@define-color accent_fg_color ${s.foreground};
@define-color accent_color ${p.accent};
@define-color destructive_bg_color ${c.color1};
@define-color destructive_fg_color ${s.foreground};
@define-color success_bg_color ${c.color2};
@define-color success_fg_color ${s.foreground};
@define-color warning_bg_color ${c.color3};
@define-color warning_fg_color ${s.background};
@define-color window_bg_color ${s.background};
@define-color window_fg_color ${s.foreground};
@define-color view_bg_color ${viewBg};
@define-color view_fg_color ${s.foreground};
@define-color headerbar_bg_color ${c.color0};
@define-color headerbar_fg_color ${s.foreground};
@define-color card_bg_color ${cardBg};
@define-color card_fg_color ${s.foreground};
@define-color dialog_bg_color ${s.background};
@define-color dialog_fg_color ${s.foreground};
@define-color popover_bg_color ${popoverBg};
@define-color popover_fg_color ${s.foreground};
@define-color sidebar_bg_color ${c.color0};
@define-color sidebar_fg_color ${s.foreground};

@define-color theme_fg_color @window_fg_color;
@define-color theme_text_color @view_fg_color;
@define-color theme_bg_color @window_bg_color;
@define-color theme_base_color @view_bg_color;
@define-color theme_selected_bg_color ${p.accent};
@define-color theme_selected_fg_color ${s.background};
@define-color insensitive_bg_color alpha(@window_bg_color, 0.85);
@define-color insensitive_fg_color alpha(@window_fg_color, 0.5);
@define-color insensitive_base_color @view_bg_color;
@define-color theme_unfocused_fg_color alpha(@window_fg_color, 0.75);
@define-color theme_unfocused_text_color @view_fg_color;
@define-color theme_unfocused_bg_color @window_bg_color;
@define-color theme_unfocused_base_color @window_bg_color;
@define-color theme_unfocused_selected_bg_color ${p.accent};
@define-color theme_unfocused_selected_fg_color ${s.background};
@define-color unfocused_insensitive_color alpha(@window_fg_color, 0.4);
@define-color borders alpha(@window_fg_color, 0.22);
@define-color unfocused_borders alpha(@window_fg_color, 0.14);
@define-color menu_bg_color @popover_bg_color;
@define-color menu_fg_color @popover_fg_color;
@define-color bg_color @theme_bg_color;
@define-color fg_color @theme_fg_color;
@define-color base_color @theme_base_color;
@define-color text_color @theme_text_color;
@define-color selected_bg_color @theme_selected_bg_color;
@define-color selected_fg_color @theme_selected_fg_color;
@define-color tooltip_bg_color @popover_bg_color;
@define-color tooltip_fg_color @popover_fg_color;
@define-color link_color @accent_bg_color;
@define-color visited_link_color ${adjustLightness(p.accent, -12)};
@define-color text_view_bg @view_bg_color;
@define-color text_view_fg @view_fg_color;
@define-color wm_title @window_fg_color;
@define-color wm_unfocused_title alpha(@window_fg_color, 0.75);
`;
}

function buildThemeCss(
	baseImport: string,
	name: string,
	overrides: string,
): string {
	return `/* Generated by novashell - Theme: ${name || "pywal"} */
@import url("${baseImport}");

${overrides}`;
}

function replaceSymlinkIfNeeded(path: string): void {
	if (!GLib.file_test(path, GLib.FileTest.IS_SYMLINK)) {
		return;
	}

	try {
		GLib.unlink(path);
	} catch (e) {
		console.error(`ColorUtils: Failed to replace symlink ${path}: ${e}`);
	}
}

function writeGeneratedFile(
	content: string,
	targetPath: string,
	prefix: string,
) {
	return copyContentInPlace(content, targetPath, prefix).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write ${targetPath}: ${e.message}`);
	});
}

export async function updateGtkColors(
	data: ColorData,
	p: DerivedPalette,
): Promise<void> {
	const overrides = buildColorOverrides(data, p);
	const gtk3ThemeCss = buildThemeCss(
		resolveBaseImport(
			GTK3_BASE_CANDIDATES,
			"resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css",
		),
		data.name ?? "pywal",
		overrides,
	);
	const gtk4ThemeCss = buildThemeCss(
		resolveBaseImport(
			GTK4_BASE_CANDIDATES,
			"resource:///org/gtk/libgtk/theme/Default/Default-dark.css",
		),
		data.name ?? "pywal",
		overrides,
	);

	const gtkSettings = `[Settings]
gtk-application-prefer-dark-theme=1
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-cursor-theme-size=24
`;

	const themeDir = `${GLib.get_user_data_dir()}/themes/novashell`;
	const gtk3ConfigDir = `${GLib.get_user_config_dir()}/gtk-3.0`;
	const gtk4ConfigDir = `${GLib.get_user_config_dir()}/gtk-4.0`;
	const gtk3ThemeDir = `${themeDir}/gtk-3.0`;
	const gtk4ThemeDir = `${themeDir}/gtk-4.0`;

	for (const dir of [
		gtk3ConfigDir,
		gtk4ConfigDir,
		gtk3ThemeDir,
		gtk4ThemeDir,
	]) {
		ensureDirectory(dir);
	}

	const gtk3SettingsPath = `${gtk3ConfigDir}/settings.ini`;
	const gtk4SettingsPath = `${gtk4ConfigDir}/settings.ini`;
	replaceSymlinkIfNeeded(gtk3SettingsPath);
	replaceSymlinkIfNeeded(gtk4SettingsPath);

	const indexTheme = `[Desktop Entry]
Type=X-GNOME-Metatheme
Name=novashell
Inherits=Adwaita

[X-GNOME-Metatheme]
GtkTheme=novashell
`;

	await Promise.all([
		writeGeneratedFile(overrides, `${gtk3ConfigDir}/gtk.css`, "novashell-gtk"),
		writeGeneratedFile(overrides, `${gtk4ConfigDir}/gtk.css`, "novashell-gtk"),
		writeGeneratedFile(
			gtk3ThemeCss,
			`${gtk3ThemeDir}/gtk.css`,
			"novashell-gtk-theme",
		),
		writeGeneratedFile(
			gtk4ThemeCss,
			`${gtk4ThemeDir}/gtk.css`,
			"novashell-gtk-theme",
		),
		writeGeneratedFile(gtkSettings, gtk3SettingsPath, "novashell-gtk-settings"),
		writeGeneratedFile(gtkSettings, gtk4SettingsPath, "novashell-gtk-settings"),
		writeFileAsync(`${themeDir}/index.theme`, indexTheme).catch((e: Error) => {
			console.error(`ColorUtils: Failed to write theme index: ${e.message}`);
		}),
	]);
}
