import GLib from "gi://GLib?version=2.0";

import { writeFileAsync } from "ags/file";
import { execAsync } from "ags/process";

import type { ColorData, DerivedPalette } from "./types";
import { ensureDirectory } from "./utils";

export function reloadTmux(): void {
	const colorsPath = `${GLib.get_user_cache_dir()}/novashell/tmux-colors.conf`;
	execAsync(["tmux", "source-file", colorsPath])
		.then(() => {
			execAsync([
				"bash",
				"-c",
				"tmux list-clients -F '#{client_name}' | while read c; do tmux refresh-client -t \"$c\" -S; done",
			]).catch(() => {});
		})
		.catch(() => {});
}

export async function generateTmuxColors(
	data: ColorData,
	p: DerivedPalette,
): Promise<void> {
	const colors = data.colors;
	const special = data.special;

	const tmuxColors = `# Generated by novashell
set -g pane-border-style "fg=${colors.color8}"
set -g pane-active-border-style "fg=${p.accent}"
set -g pane-border-lines single
set -g pane-border-indicators off
set -g message-style "fg=${special.foreground},bg=default"
set -g window-status-format "#[fg=${special.background},bg=${colors.color8}] #I #[fg=${special.foreground},bg=${p.surface0}] #{b:pane_current_path} "
set -g window-status-current-format "#[fg=${special.background},bg=${p.accent}] #I #[fg=${special.foreground},bg=${p.surface0}] #{b:pane_current_path} "
set-window-option -g window-status-separator " "
`;

	const cacheDir = `${GLib.get_user_cache_dir()}/novashell`;
	ensureDirectory(cacheDir);

	await writeFileAsync(`${cacheDir}/tmux-colors.conf`, tmuxColors).catch(
		(e) => {
			console.error(`ColorUtils: Could not write tmux colors: ${e}`);
		},
	);
}
