import GLib from "gi://GLib?version=2.0";

import { readFile, writeFileAsync } from "ags/file";

import type { ColorData, DerivedPalette } from "./types";
import { adjustLightness, ensureDirectory } from "./utils";

type ZenProfile = {
	path: string;
};

function parseProfilesIni(contents: string, zenRoot: string): ZenProfile[] {
	const profiles: ZenProfile[] = [];
	const seen = new Set<string>();

	let section = "";
	let profilePath = "";
	let isRelative = true;

	const pushProfile = () => {
		if (!section.startsWith("Profile") || !profilePath) return;

		const resolvedPath = isRelative ? `${zenRoot}/${profilePath}` : profilePath;
		if (!GLib.file_test(resolvedPath, GLib.FileTest.IS_DIR)) return;
		if (seen.has(resolvedPath)) return;

		seen.add(resolvedPath);
		profiles.push({ path: resolvedPath });
	};

	for (const rawLine of contents.split("\n")) {
		const line = rawLine.trim();
		if (!line || line.startsWith("#") || line.startsWith(";")) continue;

		if (line.startsWith("[") && line.endsWith("]")) {
			pushProfile();
			section = line.slice(1, -1);
			profilePath = "";
			isRelative = true;
			continue;
		}

		const eqIndex = line.indexOf("=");
		if (eqIndex < 1) continue;

		const key = line.slice(0, eqIndex).trim().toLowerCase();
		const value = line.slice(eqIndex + 1).trim();

		if (key === "path") profilePath = value;
		if (key === "isrelative") {
			isRelative = value === "1" || value.toLowerCase() === "true";
		}
	}

	pushProfile();

	return profiles;
}

function getZenProfiles(): ZenProfile[] {
	const zenRoot = `${GLib.get_home_dir()}/.zen`;
	const profilesIni = `${zenRoot}/profiles.ini`;

	if (!GLib.file_test(profilesIni, GLib.FileTest.EXISTS)) return [];

	try {
		const content = readFile(profilesIni);
		return parseProfilesIni(content, zenRoot);
	} catch (e) {
		console.error(`ColorUtils: Failed to read Zen profiles.ini: ${e}`);
		return [];
	}
}

function buildLogoSvg(p: DerivedPalette): string {
	return `<svg width="1024" height="1024" viewBox="0 0 1024 1024" fill="none" xmlns="http://www.w3.org/2000/svg">
  <circle cx="512" cy="512" r="340" stroke="${p.accent}" stroke-width="70"/>
  <circle cx="512" cy="512" r="224.915" stroke="${p.accent}" stroke-width="51"/>
  <circle cx="512" cy="512" r="129.018" stroke="${p.accent}" stroke-width="31"/>
</svg>
`;
}

function buildUserChrome(data: ColorData, p: DerivedPalette): string {
	const s = data.special;
	const c = data.colors;
	const selectedTabText = adjustLightness(s.foreground, -25);

	return `/* Generated by novashell - Theme: ${data.name || "pywal"} */
@media (prefers-color-scheme: dark) {
  :root {
    --zen-colors-primary: ${p.surface1} !important;
    --zen-primary-color: ${p.accent} !important;
    --zen-colors-secondary: ${p.surface0} !important;
    --zen-colors-tertiary: ${p.mantle} !important;
    --zen-colors-border: ${p.surface2} !important;
    --toolbarbutton-icon-fill: ${p.accent} !important;
    --lwt-text-color: ${s.foreground} !important;
    --toolbar-field-color: ${s.foreground} !important;
    --tab-selected-textcolor: ${selectedTabText} !important;
    --toolbar-field-focus-color: ${s.foreground} !important;
    --toolbar-color: ${s.foreground} !important;
    --newtab-text-primary-color: ${s.foreground} !important;
    --arrowpanel-color: ${s.foreground} !important;
    --arrowpanel-background: ${p.surface0} !important;
    --sidebar-text-color: ${s.foreground} !important;
    --lwt-sidebar-text-color: ${s.foreground} !important;
    --lwt-sidebar-background-color: ${p.surface0} !important;
    --toolbar-bgcolor: ${p.surface0} !important;
    --newtab-background-color: ${s.background} !important;
    --zen-themed-toolbar-bg: ${p.surface0} !important;
    --zen-themed-toolbar-bg-transparent: ${p.surface0} !important;
    --zen-main-browser-background: ${s.background} !important;
    --zen-main-browser-background-toolbar: ${p.surface0} !important;
    --zen-navigator-toolbox-background: ${p.surface0} !important;
    --zen-toolbar-element-bg: ${p.surface1} !important;
    --zen-toolbar-element-bg-hover: ${p.surface2} !important;
    --zen-urlbar-background: ${p.surface1} !important;
    --zen-colors-input-bg: ${p.surface1} !important;
    --toolbar-field-background-color: ${p.surface1} !important;
    --toolbar-field-focus-background-color: ${p.surface1} !important;
    --toolbox-bgcolor-inactive: ${p.surface0} !important;
    --zen-appcontent-border: 1px solid ${p.surface2} !important;
  }

  #navigator-toolbox,
  #main-window,
  #zen-main-app-wrapper,
  #zen-tabbox-wrapper,
  #tabbrowser-tabbox,
  #zen-appcontent-wrapper,
  #zen-appcontent-navbar-wrapper,
  #zen-appcontent-navbar-container,
  #zen-sidebar-top-buttons,
  #TabsToolbar,
  hbox#titlebar,
  #nav-bar {
    background: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
  }

  #main-window {
    --zen-themed-toolbar-bg-transparent: ${p.surface0} !important;
    --zen-navigator-toolbox-background: ${p.surface0} !important;
    --zen-main-browser-background-toolbar: ${p.surface0} !important;
  }

  #urlbar > .urlbar-background,
  .urlbar-background {
    background-color: ${p.surface1} !important;
    border: 1px solid ${p.surface2} !important;
  }

  #urlbar:hover > .urlbar-background {
    background-color: ${p.surface2} !important;
  }

  #urlbar:is([focused="true"], [open="true"], [breakout-extend="true"]) > .urlbar-background {
    background-color: ${p.surface1} !important;
    border-color: ${p.accent} !important;
    outline-color: ${p.accent} !important;
  }

  #urlbar-results,
  .urlbarView,
  .urlbarView-body-inner {
    background-color: ${p.surface0} !important;
    color: ${s.foreground} !important;
    border-color: ${p.surface2} !important;
  }

  panel,
  menupopup,
  panel[type="arrow"] {
    --panel-background: ${p.surface0} !important;
    --arrowpanel-background: ${p.surface0} !important;
    --panel-border-color: ${p.surface2} !important;
    --menu-background-color: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
    color: ${s.foreground} !important;
    border-color: ${p.surface2} !important;
    box-shadow: none !important;
  }

  panel::part(content),
  menupopup::part(content),
  panel[type="arrow"]::part(content) {
    background-color: ${p.surface0} !important;
    border-color: ${p.surface2} !important;
    box-shadow: none !important;
  }

  panelmultiview,
  panelview,
  #appMenu-popup,
  #appMenu-multiView,
  #appMenu-mainView,
  #widget-overflow,
  #customizationui-widget-panel,
  .panel-subview-body,
  .PanelUI-subView,
  .panel-viewcontainer,
  .panel-arrowcontainer,
  .panel-arrowcontent {
    background: transparent !important;
    background-color: transparent !important;
    box-shadow: none !important;
    border-color: transparent !important;
  }

  :is(
    #contentAreaContextMenu,
    #tabContextMenu,
    #toolbar-context-menu,
    #placesContext,
    #downloadsContextMenu,
    #backForwardMenu,
    #pageActionContextMenu
  ) {
    appearance: none !important;
    -moz-default-appearance: none !important;
    --panel-background: ${p.surface0} !important;
    --arrowpanel-background: ${p.surface0} !important;
    --menu-background-color: ${p.surface0} !important;
    --panel-border-color: transparent !important;
    --panel-shadow: none !important;
    --panel-shadow-margin: 0px !important;
    background: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
    color: ${s.foreground} !important;
    border: none !important;
    border-radius: 10px !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  :is(
    #contentAreaContextMenu,
    #tabContextMenu,
    #toolbar-context-menu,
    #placesContext,
    #downloadsContextMenu,
    #backForwardMenu,
    #pageActionContextMenu
  )::part(content) {
    background: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
    border: none !important;
    border-radius: 10px !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  :is(
    #contentAreaContextMenu,
    #tabContextMenu,
    #toolbar-context-menu,
    #placesContext,
    #downloadsContextMenu,
    #backForwardMenu,
    #pageActionContextMenu
  )::part(arrowscrollbox),
  :is(
    #contentAreaContextMenu,
    #tabContextMenu,
    #toolbar-context-menu,
    #placesContext,
    #downloadsContextMenu,
    #backForwardMenu,
    #pageActionContextMenu
  ) .menupopup-arrowscrollbox {
    background: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
    border: none !important;
    border-radius: 10px !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  #sidebar-box,
  #tabbrowser-arrowscrollbox-periphery {
    background-color: ${p.surface0} !important;
    border-color: ${p.surface2} !important;
  }

  #zen-sidebar-splitter,
  #sidebar-splitter,
  .zen-split-view-splitter[orient="vertical"] {
    background: ${p.surface0} !important;
    background-color: ${p.surface0} !important;
    border-color: ${p.surface0} !important;
    opacity: 1 !important;
    transition: none !important;
  }

  #zen-sidebar-splitter::before,
  #sidebar-splitter::before,
  .zen-split-view-splitter[orient="vertical"]::before {
    background: ${p.surface0} !important;
    opacity: 0 !important;
  }

  #zen-sidebar-splitter:hover,
  #sidebar-splitter:hover,
  .zen-split-view-splitter[orient="vertical"]:hover {
    background: ${p.surface0} !important;
  }

  #TabsToolbar-customization-target::after,
  .pinned-tabs-container-separator toolbarseparator {
    background: ${p.surface2} !important;
  }

  .urlbarView-row[selected],
  .urlbarView-row:hover,
  .subviewbutton:hover,
  menuitem[_moz-menuactive="true"] {
    background-color: ${p.accent}26 !important;
    color: ${s.foreground} !important;
  }

  .tab-background[selected="true"] {
    background: ${p.accent}30 !important;
  }

  .tabbrowser-tab:hover .tab-background {
    background: ${p.accent}1c !important;
  }

  #permissions-granted-icon,
  .urlbarView-url,
  .tabbrowser-tab[selected] .tab-icon-image,
  #TabsToolbar .toolbarbutton-1 {
    color: ${p.accent} !important;
  }

  .identity-color-blue { --identity-tab-color: ${c.color4} !important; --identity-icon-color: ${c.color4} !important; }
  .identity-color-turquoise { --identity-tab-color: ${c.color6} !important; --identity-icon-color: ${c.color6} !important; }
  .identity-color-green { --identity-tab-color: ${c.color2} !important; --identity-icon-color: ${c.color2} !important; }
  .identity-color-yellow { --identity-tab-color: ${c.color3} !important; --identity-icon-color: ${c.color3} !important; }
  .identity-color-orange { --identity-tab-color: ${adjustLightness(c.color3, -15)} !important; --identity-icon-color: ${adjustLightness(c.color3, -15)} !important; }
  .identity-color-red { --identity-tab-color: ${c.color1} !important; --identity-icon-color: ${c.color1} !important; }
  .identity-color-pink { --identity-tab-color: ${c.color5} !important; --identity-icon-color: ${c.color5} !important; }
  .identity-color-purple { --identity-tab-color: ${adjustLightness(c.color5, -20)} !important; --identity-icon-color: ${adjustLightness(c.color5, -20)} !important; }
}
`;
}

function buildUserContent(data: ColorData, p: DerivedPalette): string {
	const s = data.special;
	const c = data.colors;

	return `/* Generated by novashell - Theme: ${data.name || "pywal"} */
@media (prefers-color-scheme: dark) {
  @-moz-document url-prefix("about:") {
    :root {
      --in-content-page-color: ${s.foreground} !important;
      --color-accent-primary: ${p.accent} !important;
      --color-accent-primary-hover: ${adjustLightness(p.accent, 12)} !important;
      --color-accent-primary-active: ${adjustLightness(p.accent, -8)} !important;
      --in-content-page-background: ${s.background} !important;
      background-color: ${s.background} !important;
    }
  }

  @-moz-document url("about:newtab"), url("about:home") {
    :root {
      --newtab-background-color: ${s.background} !important;
      --newtab-background-color-secondary: ${p.surface0} !important;
      --newtab-element-hover-color: ${p.surface1} !important;
      --newtab-text-primary-color: ${s.foreground} !important;
      --newtab-wordmark-color: ${s.foreground} !important;
      --newtab-primary-action-background: ${p.accent} !important;
    }

    .search-wrapper .logo-and-wordmark .logo {
      background: url("zen-logo-novashell.svg") no-repeat center !important;
      display: inline-block !important;
      height: 82px !important;
      width: 82px !important;
      background-size: 82px !important;
    }

    @media (max-width: 609px) {
      .search-wrapper .logo-and-wordmark .logo {
        background-size: 64px !important;
        height: 64px !important;
        width: 64px !important;
      }
    }

    .icon,
    .card-outer:is(:hover, :focus, .active):not(.placeholder) .card-title,
    .top-site-outer .search-topsite {
      color: ${p.accent} !important;
      fill: ${p.accent} !important;
      background-color: ${p.accent} !important;
    }
  }

  @-moz-document url-prefix("about:preferences") {
    :root {
      --zen-colors-tertiary: ${p.crust} !important;
      --in-content-text-color: ${s.foreground} !important;
      --link-color: ${p.accent} !important;
      --link-color-hover: ${adjustLightness(p.accent, 10)} !important;
      --zen-colors-primary: ${p.surface1} !important;
      --in-content-box-background: ${p.surface1} !important;
      --zen-primary-color: ${p.accent} !important;
    }

    groupbox,
    moz-card {
      background: ${p.mantle} !important;
    }

    button,
    groupbox menulist {
      background: ${p.surface1} !important;
      color: ${s.foreground} !important;
    }

    .main-content {
      background-color: ${p.crust} !important;
    }
  }

  @-moz-document url-prefix("about:addons") {
    :root {
      --zen-dark-color-mix-base: ${p.crust} !important;
      --background-color-box: ${p.mantle} !important;
    }
  }

  @-moz-document url-prefix("about:protections") {
    :root {
      --zen-primary-color: ${p.mantle} !important;
      --social-color: ${c.color5} !important;
      --coockie-color: ${c.color6} !important;
      --fingerprinter-color: ${c.color3} !important;
      --cryptominer-color: ${adjustLightness(c.color4, 20)} !important;
      --tracker-color: ${c.color2} !important;
      --in-content-primary-button-background-hover: ${adjustLightness(p.surface1, 8)} !important;
      --in-content-primary-button-text-color-hover: ${s.foreground} !important;
      --in-content-primary-button-background: ${p.surface1} !important;
      --in-content-primary-button-text-color: ${s.foreground} !important;
    }

    .card {
      background-color: ${p.surface1} !important;
    }
  }
}
`;
}

async function ensureLegacyStylesheetPref(profilePath: string): Promise<void> {
	const prefLine =
		'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);';
	const userJsPath = `${profilePath}/user.js`;

	let contents = "";
	try {
		if (GLib.file_test(userJsPath, GLib.FileTest.EXISTS)) {
			contents = readFile(userJsPath);
		}
	} catch (e) {
		console.error(`ColorUtils: Failed to read ${userJsPath}: ${e}`);
	}

	if (
		contents.includes("toolkit.legacyUserProfileCustomizations.stylesheets")
	) {
		return;
	}

	const next = `${contents.trim()}\n${prefLine}\n`;
	await writeFileAsync(userJsPath, next).catch((e: Error) => {
		console.error(`ColorUtils: Failed to write Zen user.js: ${e.message}`);
	});
}

export async function updateZenTheme(
	data: ColorData,
	p: DerivedPalette,
): Promise<void> {
	const profiles = getZenProfiles();
	if (profiles.length === 0) return;

	const userChrome = buildUserChrome(data, p);
	const userContent = buildUserContent(data, p);
	const logoSvg = buildLogoSvg(p);
	const iconThemeDir = `${GLib.get_home_dir()}/.local/share/icons/hicolor/scalable/apps`;
	const zenIconPath = `${iconThemeDir}/zen-logo-novashell.svg`;

	ensureDirectory(iconThemeDir);
	await writeFileAsync(zenIconPath, logoSvg).catch((e: Error) => {
		console.error(
			`ColorUtils: Failed to write Novashell Zen icon (${zenIconPath}): ${e.message}`,
		);
	});

	await Promise.all(
		profiles.map(async (profile) => {
			const chromeDir = `${profile.path}/chrome`;
			ensureDirectory(chromeDir);

			await Promise.all([
				writeFileAsync(`${chromeDir}/userChrome.css`, userChrome).catch(
					(e: Error) => {
						console.error(
							`ColorUtils: Failed to write Zen userChrome.css (${profile.path}): ${e.message}`,
						);
					},
				),
				writeFileAsync(`${chromeDir}/userContent.css`, userContent).catch(
					(e: Error) => {
						console.error(
							`ColorUtils: Failed to write Zen userContent.css (${profile.path}): ${e.message}`,
						);
					},
				),
				writeFileAsync(`${chromeDir}/zen-logo-novashell.svg`, logoSvg).catch(
					(e: Error) => {
						console.error(
							`ColorUtils: Failed to write Zen themed logo (${profile.path}): ${e.message}`,
						);
					},
				),
				ensureLegacyStylesheetPref(profile.path),
			]);
		}),
	);
}
